# This is not a great way to create CRDS & it makes the sysadmin in me cry :(
# a customization tool that cant handle custom resource definitions see ==> https://helm.sh/docs/chart_best_practices/custom_resource_definitions/

name: crds-1password-connector
version: v0.1.0
description: A Helm chart for the 1password-connector custom resource definitions.