apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-commons-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.app }}
    spec:
      containers:
      - name: ci-commons
        image: {{ .Values.image }}
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: {{ .Values.secretName }}