apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-appbundle-app-dev
  namespace: argocd2
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    name: in-cluster
  project: appbundle-project-dev
  source:
    path: argocd/apps-children/dev
    repoURL: https://github.com/w3f/security-base-services.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true

  