environments:
  production:
  ci:
repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
releases:
  - name: postgresql-14
    chart: bitnami/postgresql
    version: 11.1.3
    namespace: postgresql
    values:
      - ./config/postgresql-14-values.yaml.gotmpl