environments:
  production:
  ci:
repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
releases:
  - name: postgresql-14
    chart: bitnami/postgresql
    version: 10.0.0
    namespace: postgresql
    # values:
    #   - ./config/postgresql-14-values.yaml.gotmpl