environments:
  production:
  ci:
repositories:
  - name: hashicorp
    url: https://helm.releases.hashicorp.com
releases:
  - name: vault
    chart: hashicorp/vault
    version: 0.19.0
    namespace: vault
    values:
      - ./config/vault-values.yaml.gotmpl