apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
  name: node-test2
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: .
    plugin:
      name: helmfile
    repoURL: 'https://github.com/w3f/polkadot-internal-deployment.git'
    targetRevision: HEAD
  syncPolicy:
    automated: null
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true

