apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: engineering-base-service
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  source:
    path: .
    repoURL: 'https://github.com/mohamedhabas11/bla.git'
    targetRevision: HEAD
    plugin:
      name: helmfile
  project: appbundle-project-dev
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
